language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  # PyPy versions
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
